USE movieordersys;
insert ignore into roles (id,name) VALUES (1,'ROLE_ADMIN');

insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) values ( 1,"The Curse of Bridge Hollow",'https://image.tmdb.org/t/p/w200/t6P9l6tcVnWLS1ADUAfkUCGQhm0.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 2,"Halloween Ends",'https://image.tmdb.org/t/p/w200/xHLwNxk7Kgpatru7advnbnBGtgf.jpg','Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life.',30,20.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 3,"Old Man",'https://image.tmdb.org/t/p/w200/hBkTcM3xhNCDaSn08RxvcFAejUJ.jpg','Deep in the woods, a lost hiker stumbles upon the cabin of an erratic and reclusive old man.',15,13.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 4,"'Accident Man: Hitman's Holiday'",'https://image.tmdb.org/t/p/w200/8XF5EIDUOZv1p9orukdyERvv2Qn.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 5,"Rosaline",'https://image.tmdb.org/t/p/w200/jQHrbzVy6ptopxqUohV6PcmmVcY.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 6,"Bullet Train",'https://image.tmdb.org/t/p/w200/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 7,"Top Gun: Maverick",'https://image.tmdb.org/t/p/w200/62HCnUTziyWcpDaBO2i1DX17ljH.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
insert ignore into movies ( id,NAME,poster,DESCRIPTION,price,quantity) VALUES ( 8,"Werewolf by Night",'https://image.tmdb.org/t/p/w200/1n2q0Y1pX8PkQh9imqGbNH7Bw4q.jpg','The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.',20,15.0);
